feat: Improve visibility of credit and debit
Brixel/HaSpMan pull request #100
Opened 2022-11-15 21:54 UTC by BerendWouters

2022-11-15 21:55 UTC, BerendWouters commented
This resolves #64

2022-11-16 09:37 UTC, vyruz1986 requested changes

2022-11-16 09:37 UTC, vyruz1986 commented on Web/Pages/Transactions/Transactions.razor
> +        return transactionTypeGroup == TransactionTypeGroup.Credit ? "background-color: rgba(255,0,0,0.2)" : "background-color: rgba(0,255,0,0.2)";
We should use MudBlazor's theme colors here : https://mudblazor.com/features/colors

2022-11-16 09:37 UTC, vyruz1986 commented on Web/Pages/Transactions/Transactions.razor
> +                      ValueChanged="@(OnSearch)">
Nice!

2022-11-16 21:06 UTC, vyruz1986 approved these changes

2022-11-16 21:07 UTC, merged