Feature/#54
Brixel/HaSpMan pull request #102
Opened 2022-11-25 22:20 UTC by BerendWouters

2023-01-10 21:46 UTC, vyruz1986 requested changes
I don't like how this is very UI-driven. I would rather see a `MembershipFeePaid` event being published, which is then picked up by a `ExtendMembershipHandler` handler which would extend the expiry date accordingly.
This would make for a more flexible system, as we could in the future have e.g. a `ThankMemberForPayingMembershipFee` handler which sends an email to the member thanking them for paying their fee.

2023-01-10 21:46 UTC, vyruz1986 commented on Web/Pages/Transactions/EditTransaction.razor
> +                //Transaction.NewExpirationDate = member.MembershipExpiryDate.Value.AddMonths(amountOfMonths).Date;
This shouldn't be commented out I think?

2023-01-10 21:46 UTC, vyruz1986 commented on Web/Pages/Transactions/EditTransaction.razor
> +    private async Task ChangeMembershipFee()
This doesn't seem to be called anywhere?

2023-02-14 19:02 UTC, BerendWouters commented
> I don't like how this is very UI-driven. I would rather see a `MembershipFeePaid` event being published, which is then picked up by a `ExtendMembershipHandler` handler which would extend the expiry date accordingly. This would make for a more flexible system, as we could in the future have e.g. a `ThankMemberForPayingMembershipFee` handler which sends an email to the member thanking them for paying their fee.

I'm not really familiar with events in "The Grand Scheme of Things Called DDD", so I'll have to look into that.

2023-02-15 09:12 UTC, vyruz1986 commented
> > I don't like how this is very UI-driven. I would rather see a `MembershipFeePaid` event being published, which is then picked up by a `ExtendMembershipHandler` handler which would extend the expiry date accordingly. This would make for a more flexible system, as we could in the future have e.g. a `ThankMemberForPayingMembershipFee` handler which sends an email to the member thanking them for paying their fee.
> 
> I'm not really familiar with events in "The Grand Scheme of Things Called DDD", so I'll have to look into that.

Sure, let me know if you'd like to pair program on this or if you would rather have me do it

2023-02-25 00:19 UTC, vyruz1986 approved these changes

2023-02-25 00:19 UTC, merged