Feature/#1 remove member
Brixel/HaSpMan pull request #51
Opened 2022-04-17 19:28 UTC by BerendWouters

Adds the long awaited feature to remove members.
Includes a confirmation dialog.

Not included, because to be discussed: audit trailing of the removal. An attempt was made by introducing a SystemAuditEvent, but it feels like I do need to validate this data model design with someone else.

2022-06-03 18:02 UTC, BerendWouters commented
*bump* @vyruz1986 @Joren-Thijs

2022-06-27 20:27 UTC, vyruz1986 requested changes
Not a fan of the commented SystemAudit code, either make it work or put it into a separate branch for future use

2022-06-28 12:30 UTC, vyruz1986 requested changes
There is still a lot of SystemAuditEvent code in comments, please remove if not being used

2022-06-28 22:14 UTC, vyruz1986 requested changes

2022-06-28 22:14 UTC, vyruz1986 commented on Persistence/HaSpManContext.cs
> +    //public class HaspmanContextFactory : IDesignTimeDbContextFactory<HaSpManContext>
![GetRidOfItRichardWilliamsGIF](https://user-images.githubusercontent.com/3620147/176310899-b0854960-a8ee-4f0a-a2d5-7ff4ffb4441f.gif)

2022-07-03 11:14 UTC, vyruz1986 approved these changes

2022-07-03 11:14 UTC, merged